export const DEFAULT_PLANS = [
  {
    name: 'Basic Plan',
    slug: 'basic',
    minimumAmount: 100,
    maximumAmount: 3999,
    returnPercentage: 10,
    durationHours: 24,
    referralPercentage: 5,
    principalReturn: true,
    description: 'Designed for beginners and exploratory digital asset allocations with standard 24-hour liquidity.',
    status: 'ACTIVE' as const,
    featured: false,
  },
  {
    name: 'Gold Plan',
    slug: 'gold',
    minimumAmount: 10000,
    maximumAmount: 14999,
    returnPercentage: 55,
    durationHours: 72,
    referralPercentage: 5,
    principalReturn: true,
    description: 'Institutional-grade structured yield plan with enhanced performance metrics and 72-hour cycle.',
    status: 'ACTIVE' as const,
    featured: true,
  },
  {
    name: 'Ultimate Plan',
    slug: 'ultimate',
    minimumAmount: 15000,
    maximumAmount: 0,
    returnPercentage: 100,
    durationHours: 24,
    referralPercentage: 5,
    principalReturn: true,
    description: 'High-tier strategic asset deployment maximizing computational liquidity across multi-market nodes.',
    status: 'ACTIVE' as const,
    featured: false,
  },
] as const;